### ISSUE TITLE
Is there anyway to check out the reconstructed 3d scene online?

### ISSUE THREAD

**Issue by jeezrick** [MisEty/RTG-SLAM#7]
Hi, I wonder if you know Is there anyway to Check out the 3d reconstruction's quality during the slam process. 

You can toggle around and zoom in ...

I think I see it in your video in github page, would you mind share your method? thanks.

**Comment by MisEty** [comment]
Yes, similar to the `SIBR_remoteGaussian_app` in 3DGS, we have implemented an online visualization tool. However, due to the large amount of code in this project and the fact that we only prepared a Windows version, we have not yet finished organizing the code, so it will not be open-sourced recently. If you're interested, you can modify the `SIBR_remoteGaussian_app` as a reference, or use our rendering functions to save images for visualization during the SLAM process.

**Comment by jeezrick** [comment]
Thanks for the reply.
I utilized a viewer to inspect the ply file post-mapping. 
However, the TUM-RGBD scene appears underwhelming; it is filled with floaters and semi-transparent Gaussians, which I assumed would be eliminated according to the methods you described in the paper. Should this outcome be anticipated?

![00000](https://github.com/MisEty/RTG-SLAM/assets/47274616/6b596cd4-5a57-4c22-a4a6-a123b0d18166)

**Comment by jeezrick** [comment]
I also ran your dataset 'hotel'; it's pretty good, as seen on your GitHub page. So I wonder what the key factor is here: the hyperparameters of Gaussian mapping, the image FPS, or the depth quality? Can you shed some light?

**Comment by MisEty** [comment]
The depth quality is very important because we set the positions of Gaussians by the depth loss term. If Gaussians are put into wrong places, the SHs and shapes may be strange to fit the color images. The hyperparameters of Gaussian mapping also need to be changed according to the data. For example, if the image FPS is high, you can set larger `gaussian_update_frame` and if the scene is complex, you need to set larger `gaussian_update_iter`.
